### ISSUE TITLE
Step 1 of createContextualFragment is not enough

### ISSUE THREAD

**Issue by nox** [w3c/DOM-Parsing#17]
https://w3c.github.io/DOM-Parsing/#idl-def-range-createcontextualfragment(domstring)

The intent of the step is to let `element` be an instance of `Element` at the end of step 1, but if the context object's start node is a `Comment` that is a child of a `Document` or `DocumentFragment`, `element` will not be an `Element`.

**Comment by nox** [comment]
How can it be null? The specification doesn't actually say that `element` should be an instance of `Element`, so `element` in step 1 in that case is just bound to a `Document` or `DocumentFragment` instance.

**Comment by ArkadiuszMichalski** [comment]
Hmm I check this version https://www.w3.org/TR/DOM-Parsing/#dfn-dom-range-createcontextualfragment, this from git is different: "node's parent"...

**Comment by nox** [comment]
Hah! Nice. Yeah this would clear it up, though it should probably state something like "or null if there is no parent element".

**Comment by ArkadiuszMichalski** [comment]
But per definition [parent element] (https://dom.spec.whatwg.org/#parent-element) can be null so it's not neccessary.

**Comment by nox** [comment]
Oh right! Disregard my last comment then.
