### ISSUE TITLE
HTML Entities & Serialization output (code versus rendered)

### ISSUE THREAD

**Issue by jabcreations** [w3c/DOM-Parsing#20]
1.) The HTML entities such as & amp; and & gt; are not compatible with XML parsers and should not even be on the specification; user agents should only convert to numeric entities only. To test this create a *.xhtml file, add such entities and open the file in Firefox.

2.) Serializing should include a second flag to either convert HTML entities to text output (e.g. & #160;) or render (entity 160 converts to a space).

My platform's editor can switch between rich/visual and code editing. Unfortunately I haven't determined any direct way of outputting HTML entities as code (they are always rendered) which is ironic since serialization is supposed to output the code instead of render it. However since people will want the output to either be pure code or to render HTML entities a second flag should be added for the serializeToString method.

**Comment by annevk** [comment]
> The HTML entities such as & amp; and & gt; are not compatible with XML parsers and should not even be on the specification

That is not true…
