### ISSUE TITLE
innerHTML should be defined on ShadowRoot interface in addition to Element interface

### ISSUE THREAD

**Issue by rniwa** [w3c/DOM-Parsing#21]
In the world where `ShadowRoot` interface is merged into DOM (as done in the [WHATWG version](https://dom.spec.whatwg.org/#interface-shadowroot)), it's more natural for the DOM parsing & serialization spec to define `innerHTML` IDL attribute on both `Element` and `ShadowRoot` interfaces.

**Comment by foolip** [comment]
FWIW, Chromium and WebKit both have this already. (I came here trying to figure out what to do about that.)

**Comment by domenic** [comment]
The hard part here is figuring out the context element. Once we do that, it's easy to spec. @rniwa @tkent-google @smaug---- can you let us know what your implementations of ShadowRoot's innerHTML do in that regard?

**Comment by rniwa** [comment]
WebKit uses the host element as the context element.

**Comment by smaug----** [comment]
(Github is behaving oddly today)

Gecko uses host as context, https://searchfox.org/mozilla-central/rev/0ec9f5972ef3e4a479720630ad7285a03776cdfc/dom/base/FragmentOrElement.cpp#2309-2313

**Comment by tkent-google** [comment]
Blink also uses the host element.

**Comment by rniwa** [comment]
Sounds like this is ready to be spec'ed as such then.
