### ISSUE TITLE
Define the origin of the documents returned from DOMParser

### ISSUE THREAD

**Issue by Ms2ger** [w3c/DOM-Parsing#24]

**Comment by annevk** [comment]
If we don't define it then it would just be the default, an opaque origin. Seems okayish? Did you test implementations?

**Comment by Ms2ger** [comment]
Does that mean you can't access the DOM of it at all?

**Comment by annevk** [comment]
I don't think so. We use the origin of the global for that, no?

**Comment by domenic** [comment]
@annevk @Ms2ger what does this affect, in documents without a browsing context? What tests could we write for this?

**Comment by domenic** [comment]
Given that we're removing document.origin, it seems this is unobservable and so leaving it at its default value is fine. I'll close this, but if you think we should add a note explaining that we're leaving it at its default value to https://github.com/whatwg/html/pull/5190, please comment over there.
