### ISSUE TITLE
should createContextualFragment be added in Document / DocumentFragment?

### ISSUE THREAD

**Issue by caub** [w3c/DOM-Parsing#33]
instead of in Range prototype, I think it could be great to just do `document.createContextualRange('<br>')`

**Comment by annevk** [comment]
It would help if you started with a problem statement, before going to what the solution might look like.  See also https://whatwg.org/faq#adding-new-features.

**Comment by annevk** [comment]
It's a legacy API that all browsers were forced to adopt. I don't recall reading about the design history.

**Comment by caub** [comment]
I think there's some work concerning `<template>` that could make html parsing easier. Yes I knex Range and editing APIs are more than 15 years old, but I was wondering if this particular method could be extracted in a more accessible class/object

let's close it, maybe for now
