### ISSUE TITLE
Specify the relationship between the Text Declaration and document.characterSet

### ISSUE THREAD

**Issue by DavidBruant** [w3c/DOM-Parsing#34]
- [Text Declaration](https://www.w3.org/TR/2008/REC-xml-20081126/#sec-TextDecl)
- [document.characterSet](https://dom.spec.whatwg.org/#dom-document-characterset)

```js
const inXMLStr = `<?xml version="1.0" encoding="ISO-8859-1"?> <x/>`
  
const doc = (new DOMParser()).parseFromString(inXMLStr, 'text/xml')
  
console.log(doc.characterSet)
```

Both Firefox and Chrome say 'UTF-8' ignoring completely the `encoding="ISO-8859-1"`. Totally fine behavior as far as I'm concerned, I haven't tested in other browsers

**Comment by domenic** [comment]
I've added a note about this to https://github.com/whatwg/html/pull/5190.
