### ISSUE TITLE
parseFromString() should be use case-insensitive MIME type matching

### ISSUE THREAD

**Issue by dbates-wk** [w3c/DOM-Parsing#40]
The DOM Parsing spec does not specify whether the type argument passed to parseFromString() is case-sensitively or case-insensitively matched against MIME types. In absence of such a mention the spec. text falls back to a general statement that a reader should assume case-sensitive matching. It does not make sense (if it does make sense then please explain why? Did browsers botch this for this Web API? I haven’t checked, yet) that we should be performing case-sensitive matching for MIME types. MIME types are defined to be case-insensitive by <https://tools.ietf.org/html/rfc2045>. 

I suggest we change the spec. text:

> The DOMParser constructor must return a new DOMParser object.
> The parseFromString(str, type) method must run these steps, depending on type:
>
> "text/html"
> ...

To something like, highlighting for emphasis:

> The DOMParser constructor must return a new DOMParser object.
> The parseFromString(str, type) method must run these steps, depending on type **case-insensitively matching one of the following MIME types**:
>
> "text/html"
> ...

**Comment by annevk** [comment]
Well, now it can be an enum: https://w3c.github.io/DOM-Parsing/#the-domparser-interface. There's no ASCII-case-insensitive enums. It's also seen as a somewhat legacy API so I'm not sure it makes sense to complicate things here.

**Comment by dbates-wk** [comment]
> Well, now it can be an enum: https://w3c.github.io/DOM-Parsing/#the-domparser-interface. There's no ASCII-case-insensitive enums. It's also seen as a somewhat legacy API so I'm not sure it makes sense to complicate things here.

I see. It seems ridiculous that this API case-sensitively matches MIME type based on the definition of MIME type. I haven't checked Edge, but Mac Chrome Canary Version 74.0.3686.0, Mac Firefox 64.0.2, Safari Version 12.0 (14606.1.36.1.2) seems to be unhappy and throw an exception when I tried to evaluate:

`(new DOMParser).parseFromString("<h1>Hello</h1>", "text/HTML")`

So, there is agreement in case-sensitively matching the MIME type passed to parseFromString() :/

Still have this question:

>  Did browsers botch this for this Web API? 

And another: Why did browsers vendors choose to perform case-sensitive matching? Was this fall out from use of WebIDL enum? Did WebIDL enum exist at the time this API was first introduced?

**Comment by annevk** [comment]
I'm not sure. I think this API might have come from Firefox and they might have had a safelist of MIME types initially they would compare against literally and throw otherwise?

Note that there's other places where we don't allow the full complexity of MIME types, though case-insensitive matching is often done. E.g., `<script type=text/javascript;>` will not execute. For new places we should probably not follow those patterns, but changing these old places is a lot of risk for little-to-no reward.
