### ISSUE TITLE
Improve definition of URL for Documents created by DOMParser

### ISSUE THREAD

**Issue by Ms2ger** [w3c/DOM-Parsing#46]
The spec currently refers to the "active document", which is a property of a browsing context. However, it doesn't define which browsing context it's getting the "active document" from.

However, this doesn't appear to be the correct concept in the first place. Gecko, Chrome and WebKit all seem to use the URL of the [relevant global](https://html.spec.whatwg.org/multipage/webappapis.html#concept-relevant-global)'s [associated Document](https://html.spec.whatwg.org/multipage/window-object.html#concept-document-window).

In particular, this difference is significant if the browsing context is navigated. In that case, the "active document" would change, and the spec would suggest using the URL the BC was navigated to. All browsers I tested use the pre-navigation URL instead.

**Comment by Ms2ger** [comment]
Tests: https://github.com/web-platform-tests/wpt/pull/15548

**Comment by domenic** [comment]
This is being done in https://github.com/whatwg/html/pull/5190
